name: zdata
description: "zdata compresses your Android apps' data so it'll take less space"

dependencies:
  android_app_info: ^0.0.3
  path_provider: any
  url_launcher: any
  path: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - bin-arm/fusecompress
    - bin-arm/fusermount
    - bin-x86/fusecompress
    - bin-x86/fusermount
    - script/mount.sh
    - script/mountall.sh
    - script/umount.sh
